[package]
name = "controlay"
version = "1.1.1"
edition = "2024"
authors = ["arounre"]
description = "Receiver for Controlay: Emulate game controllers on PC using your Android phone as a wireless bridge."
homepage = "https://github.com/arounre/controlay"
repository = "https://github.com/arounre/controlay"
documentation = "https://github.com/arounre/controlay#usage"
license = "GPL-3.0-or-later"
readme = "README.md"
keywords = ["controller", "emulation", "gaming", "network", "android"]
categories = ["emulators", "hardware-support"]

[dependencies]
eframe = { version = "0.34.2", default-features = false, features = [
    "persistence",
    "glow",
] }
egui = "0.34.2"
egui_commonmark = { version = "0.23.0", default-features = false }
hostname = "0.4.2"
local-ip-address = "0.6.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
tray-icon = "0.24.0"
single-instance = "0.3.3"
native-dialog = "0.9.6"
reqwest = { version = "0.13.3", features = ["blocking", "json"] }
semver = "1.0.28"
anyhow = "1.0.102"
notify-rust = "4.17.0"
tokio = { version = "1.52.3", features = ["full"] }

[target.'cfg(target_os = "windows")'.dependencies]
vigem-rust = "0.1.1"

[build-dependencies]
image = { version = "0.25.10", default-features = false, features = ["png"] }

[target.'cfg(target_os = "windows")'.build-dependencies]
winres = "0.1.12"


[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[package.metadata.packager]
product-name = "Controlay"
identifier = "com.arounre.controlay"
formats = ["nsis", "wix"]

[[package.metadata.packager.binaries]]
path = "controlay.exe"
main = true

[package.metadata.release]
publish = false
push = true
tag-name = "v{{version}}"
