[alias]
update-thirdparty = ["about", "generate", "-o", "thirdparty.md", "about.hbs"]

pack = ["packager", "--release"]
pack-nsis = ["packager", "--release", "--formats", "nsis"]
pack-msi = ["packager", "--release", "--formats", "wix"]
